# Disable automatic runs of this pipeline when changes are pushed to the repository.
trigger: none

# Disable automatic runs of this pipeline when a PR is create.
pr: none

# Add the pipeline that builds the packages as a resource.
# This allows the deployment pipeline to be triggered whenever
# the build pipeline completes.
# Add common-ci repo as a resource to access common templates.
resources:
  pipelines:
  - pipeline: build-pipeline   # The name for the triggering build pipeline within this script
    source: device-detection-php-onpremise-tag-repository # Name of the pipeline
    trigger: true 
  repositories:
  - repository: ciTemplates # Id of the repository used to reference to in this script
    type: git
    name: common-ci # Name of the actual repository

variables:
  # Include shared variables
- template: shared-variables.yml
- name: deployRunTests
  value: 'On'

stages:

- template: data-stage.yml
  parameters:
    runTests: variables['deployRunTests']
    
- template: shared-build-and-test-stage.yml
  parameters:
    # Production buildType parameter indicates that build and test
    # stage will use released packages for pipeline dependencies.
    # This is the final check before deploy externally.
    buildType: 'Production'
    imageName: $(linuxImage)
    runTests: variables['deployRunTests']

# Publish to Github 
- template: shared-publish-github-stage.yml@ciTemplates
  parameters:
    imageName: $(linuxImage)
    branchName: 'refs/heads/master'