param (
    [Parameter(Mandatory=$true)]
    [string]$RepoName
)
$ErrorActionPreference = 'Stop'

# The shared Selenium contract tests need DeviceType and the JavaScript
# overrides for screen size, which the Lite data file does not have, so they
# run against the TAC data file that fetch-assets downloads when a device
# detection licence is given.
$dataFile = "$PWD/assets/TAC-HashV41.hash"
if (!(Test-Path $dataFile)) {
    Write-Output "::warning file=$($MyInvocation.ScriptName),line=$($MyInvocation.ScriptLineNumber),title=No On-Premise Data File::On-Premise Data File wasn't found, so the Selenium tests will not run."
    return
}

# Include php.ini with extension settings, generated by build-project. It
# already points the engine at the TAC data file. The example also reads the
# data file from 51DEGREES_DD_PATH, and that is set to the same file here so
# the two agree. Because they name the same file, useDataFileFromEnv finds
# the engine already loaded from it and returns without reloading, so this
# run does not cover the reload itself.
$sep = [IO.Path]::PathSeparator
$env:PHP_INI_SCAN_DIR = "$sep$PWD/$RepoName"
[Environment]::SetEnvironmentVariable('51DEGREES_DD_PATH', $dataFile)

# 8096 is the port the cloud example uses in the cloud repository's CI, and
# the unit and configuration tests use 3000 and 3002, so use another one.
$port = 8097
$example = $null

Write-Host 'Running Selenium tests against the on-premise web example...'
try {
    # Start this repository's on-premise web example with the PHP built-in
    # server, using the example script as the router.
    Push-Location $RepoName
    try {
        $example = php -S "localhost:$port" examples/onpremise/gettingStartedWeb.php 2>&1 &
    } finally {
        Pop-Location
    }

    # Get the shared contract tests.
    if (-not (Test-Path selenium-api-tests)) {
        git clone --depth 1 https://github.com/51Degrees/selenium-api-tests.git
        if ($LASTEXITCODE -ne 0) {
            throw "Failed to clone the Selenium tests"
        }
    }

    # Wait for the example to come up. The engine loads the whole data file
    # into memory before the server listens, so allow time for that.
    curl -sS --fail -o /dev/null --retry 30 --retry-delay 2 --retry-connrefused "http://localhost:$port/"
    if ($LASTEXITCODE -ne 0) {
        throw "The on-premise web example did not start on port $port"
    }

    # The suite reads the cloud address at start up and needs a resource key
    # to be set, even though the on-premise example uses neither. The tests
    # pass both to the example they start, and an example given in
    # EXAMPLE_URL is already running, so nothing is sent anywhere.
    $env:CLOUD_ROOT_URL = "https://cloud.51degrees.com/"
    $env:PAID_RESOURCE_KEY = "not-used-by-the-on-premise-example"
    $env:EXAMPLE_URL = "http://localhost:$port"
    $env:EXAMPLE_LANG = 'php'
    dotnet test selenium-api-tests -c Release --filter TestCategory=Contract
    if ($LASTEXITCODE -ne 0) {
        throw "The Selenium contract tests failed against the on-premise web example"
    }
} catch {
    # Show what the example serves as its client-side script and JSON, and
    # whether the script parses, because a script that fails to parse leaves
    # no fod object for the tests to wait on.
    $agent = 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1'
    foreach ($resource in '51Degrees.core.js', 'json') {
        $file = "$PWD/example-$resource.txt"
        curl -sS -o $file -A $agent "http://localhost:$port/$resource"
        if (Test-Path $file) {
            $content = [string](Get-Content -Raw $file)
            Write-Host ">>> start of /$resource ($($content.Length) characters) >>>"
            Write-Host $content.Substring(0, [Math]::Min(1500, $content.Length))
            Write-Host '<<< end of extract <<<'
        }
    }
    if ((Test-Path "$PWD/example-51Degrees.core.js.txt") -and
        (Get-Command node -ErrorAction SilentlyContinue)) {
        Copy-Item "$PWD/example-51Degrees.core.js.txt" "$PWD/example-core.js"
        node --check "$PWD/example-core.js"
    }
    if ($example) {
        Write-Host '>>> example app output >>>'
        Receive-Job $example | Out-Host
        Write-Host '<<< app output <<<'
    }
    throw
} finally {
    if ($example) {
        Remove-Job -Force $example
    }
}
