param (
    [Parameter(Mandatory=$true)]
    [string]$RepoName
)

if (!(Test-Path assets/TAC-HashV41.hash)) {
    Write-Output "::warning file=$($MyInvocation.ScriptName),line=$($MyInvocation.ScriptLineNumber),title=No On-Premise Data File::On-Premise Data File wasn't found, so unit tests will not run."
    return
}

# Include php.ini with extension settings, generated by build-project
$sep = [IO.Path]::PathSeparator
$env:PHP_INI_SCAN_DIR = "$sep$PWD/$RepoName"

./php/run-unit-tests.ps1 -RepoName $RepoName

# Run configuration tests. These exercise the engine under the PHP built-in
# server. They previously failed on macOS (see issue #38) and so were limited
# to Linux, but the underlying problem is now fixed by always using the
# in-memory MaxPerformance profile, so they run on every platform.
& $RepoName/configuration-tests/testConcurrencySetting.ps1 -BaseIniFilePath $PWD/$RepoName/php.ini || $(throw "concurrency configuration tests failed")
& $RepoName/configuration-tests/testPerformanceProfileSetting.ps1 -BaseIniFilePath $PWD/$RepoName/php.ini || $(throw "performance_profile configuration tests failed")

# Prove why MaxPerformance is enforced: a streaming profile fails across a fork
# (as used by process managers) while the in-memory profile is safe.
& $RepoName/configuration-tests/testForkSafety.ps1 -RepoName $RepoName || $(throw "fork-safety test failed")

exit $LASTEXITCODE
