param (
    [Parameter(Mandatory=$true)]
    [string]$RepoName,
    [Parameter(Mandatory=$true)]
    [string]$Name,
    [boolean]$RunPerformance = $True
)

if (!$RunPerformance) {
    Write-Output "Skipping performance tests"
    exit 0
}

# Include php.ini with extension settings, generated by build-project
$sep = [IO.Path]::PathSeparator
$env:PHP_INI_SCAN_DIR = "$sep$PWD/$RepoName"
$perfSummary = New-Item -ItemType directory -Path $RepoName/test-results/performance-summary -Force

Push-Location $RepoName
try {
    Write-Output "Running performance tests"
    $resultsRaw = php performance-tests/benchmark.php ../assets/"20000 User Agents.csv" --output || $(throw "benchmark failed")
    Write-Output $resultsRaw

    $results = $resultsRaw | ConvertFrom-Json
    @{
        HigherIsBetter = @{
            DetectionsPerSecond = $results.DetectionsPerSecond
        };
        LowerIsBetter = @{
            AvgMillisecsPerDetection = $results.AvgMillisecsPerDetection
        }
    } | ConvertTo-Json | Out-File $perfSummary/results_$Name.json
} finally {
    Pop-Location
}
