param (
    [Parameter(Mandatory=$true)]
    [string]$RepoName
)

# Include php.ini with extension settings, generated by build-project
$sep = [IO.Path]::PathSeparator
$env:PHP_INI_SCAN_DIR = "$sep$PWD/$RepoName"

./php/run-unit-tests.ps1 -RepoName $RepoName

exit $LASTEXITCODE
