var annotated =
[
    [ "fiftyone", null, [
      [ "pipeline", null, [
        [ "core", null, [
          [ "AspectPropertyValue", "classfiftyone_1_1pipeline_1_1core_1_1_aspect_property_value.html", "classfiftyone_1_1pipeline_1_1core_1_1_aspect_property_value" ],
          [ "BasicListEvidenceKeyFilter", "classfiftyone_1_1pipeline_1_1core_1_1_basic_list_evidence_key_filter.html", "classfiftyone_1_1pipeline_1_1core_1_1_basic_list_evidence_key_filter" ],
          [ "Constants", "classfiftyone_1_1pipeline_1_1core_1_1_constants.html", "classfiftyone_1_1pipeline_1_1core_1_1_constants" ],
          [ "ElementData", "classfiftyone_1_1pipeline_1_1core_1_1_element_data.html", "classfiftyone_1_1pipeline_1_1core_1_1_element_data" ],
          [ "ElementDataDictionary", "classfiftyone_1_1pipeline_1_1core_1_1_element_data_dictionary.html", "classfiftyone_1_1pipeline_1_1core_1_1_element_data_dictionary" ],
          [ "Evidence", "classfiftyone_1_1pipeline_1_1core_1_1_evidence.html", "classfiftyone_1_1pipeline_1_1core_1_1_evidence" ],
          [ "EvidenceKeyFilter", "classfiftyone_1_1pipeline_1_1core_1_1_evidence_key_filter.html", "classfiftyone_1_1pipeline_1_1core_1_1_evidence_key_filter" ],
          [ "FlowData", "classfiftyone_1_1pipeline_1_1core_1_1_flow_data.html", "classfiftyone_1_1pipeline_1_1core_1_1_flow_data" ],
          [ "FlowElement", "classfiftyone_1_1pipeline_1_1core_1_1_flow_element.html", "classfiftyone_1_1pipeline_1_1core_1_1_flow_element" ],
          [ "JavascriptBuilderElement", "classfiftyone_1_1pipeline_1_1core_1_1_javascript_builder_element.html", "classfiftyone_1_1pipeline_1_1core_1_1_javascript_builder_element" ],
          [ "JsonBundlerElement", "classfiftyone_1_1pipeline_1_1core_1_1_json_bundler_element.html", "classfiftyone_1_1pipeline_1_1core_1_1_json_bundler_element" ],
          [ "Logger", "classfiftyone_1_1pipeline_1_1core_1_1_logger.html", "classfiftyone_1_1pipeline_1_1core_1_1_logger" ],
          [ "Messages", "classfiftyone_1_1pipeline_1_1core_1_1_messages.html", "classfiftyone_1_1pipeline_1_1core_1_1_messages" ],
          [ "Pipeline", "classfiftyone_1_1pipeline_1_1core_1_1_pipeline.html", "classfiftyone_1_1pipeline_1_1core_1_1_pipeline" ],
          [ "PipelineBuilder", "classfiftyone_1_1pipeline_1_1core_1_1_pipeline_builder.html", "classfiftyone_1_1pipeline_1_1core_1_1_pipeline_builder" ],
          [ "SequenceElement", "classfiftyone_1_1pipeline_1_1core_1_1_sequence_element.html", "classfiftyone_1_1pipeline_1_1core_1_1_sequence_element" ],
          [ "SetHeaderElement", "classfiftyone_1_1pipeline_1_1core_1_1_set_header_element.html", "classfiftyone_1_1pipeline_1_1core_1_1_set_header_element" ],
          [ "Utils", "classfiftyone_1_1pipeline_1_1core_1_1_utils.html", "classfiftyone_1_1pipeline_1_1core_1_1_utils" ]
        ] ],
        [ "devicedetection", null, [
          [ "Constants", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_constants.html", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_constants" ],
          [ "DeviceDetectionOnPremise", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_device_detection_on_premise.html", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_device_detection_on_premise" ],
          [ "Messages", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_messages.html", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_messages" ],
          [ "SwigData", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_swig_data.html", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_swig_data" ],
          [ "SwigHelpers", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_swig_helpers.html", "classfiftyone_1_1pipeline_1_1devicedetection_1_1_swig_helpers" ]
        ] ],
        [ "engines", null, [
          [ "AspectData", "classfiftyone_1_1pipeline_1_1engines_1_1_aspect_data.html", "classfiftyone_1_1pipeline_1_1engines_1_1_aspect_data" ],
          [ "AspectDataDictionary", "classfiftyone_1_1pipeline_1_1engines_1_1_aspect_data_dictionary.html", "classfiftyone_1_1pipeline_1_1engines_1_1_aspect_data_dictionary" ],
          [ "CloudEngineBase", "classfiftyone_1_1pipeline_1_1engines_1_1_cloud_engine_base.html", null ],
          [ "DataKeyedCache", "classfiftyone_1_1pipeline_1_1engines_1_1_data_keyed_cache.html", "classfiftyone_1_1pipeline_1_1engines_1_1_data_keyed_cache" ],
          [ "Engine", "classfiftyone_1_1pipeline_1_1engines_1_1_engine.html", "classfiftyone_1_1pipeline_1_1engines_1_1_engine" ],
          [ "MissingPropertyMessages", "classfiftyone_1_1pipeline_1_1engines_1_1_missing_property_messages.html", "classfiftyone_1_1pipeline_1_1engines_1_1_missing_property_messages" ],
          [ "MissingPropertyReason", "classfiftyone_1_1pipeline_1_1engines_1_1_missing_property_reason.html", "classfiftyone_1_1pipeline_1_1engines_1_1_missing_property_reason" ],
          [ "MissingPropertyService", "classfiftyone_1_1pipeline_1_1engines_1_1_missing_property_service.html", "classfiftyone_1_1pipeline_1_1engines_1_1_missing_property_service" ],
          [ "SessionCache", "classfiftyone_1_1pipeline_1_1engines_1_1_session_cache.html", "classfiftyone_1_1pipeline_1_1engines_1_1_session_cache" ],
          [ "Tracker", "classfiftyone_1_1pipeline_1_1engines_1_1_tracker.html", "classfiftyone_1_1pipeline_1_1engines_1_1_tracker" ]
        ] ]
      ] ]
    ] ],
    [ "ArrayLogger", "class_array_logger.html", "class_array_logger" ],
    [ "AstrologyFlowElement", "class_astrology_flow_element.html", "class_astrology_flow_element" ],
    [ "BoolValueSwig", "class_bool_value_swig.html", "class_bool_value_swig" ],
    [ "CollectionConfigSwig", "class_collection_config_swig.html", "class_collection_config_swig" ],
    [ "ComponentMetaDataCollectionSwig", "class_component_meta_data_collection_swig.html", "class_component_meta_data_collection_swig" ],
    [ "ComponentMetaDataSwig", "class_component_meta_data_swig.html", "class_component_meta_data_swig" ],
    [ "ConfigBaseSwig", "class_config_base_swig.html", "class_config_base_swig" ],
    [ "ConfigDeviceDetectionSwig", "class_config_device_detection_swig.html", "class_config_device_detection_swig" ],
    [ "ConfigHashSwig", "class_config_hash_swig.html", "class_config_hash_swig" ],
    [ "Date", "class_date.html", "class_date" ],
    [ "DoubleValueSwig", "class_double_value_swig.html", "class_double_value_swig" ],
    [ "EngineBaseSwig", "class_engine_base_swig.html", "class_engine_base_swig" ],
    [ "EngineDeviceDetectionSwig", "class_engine_device_detection_swig.html", "class_engine_device_detection_swig" ],
    [ "EngineHashSwig", "class_engine_hash_swig.html", "class_engine_hash_swig" ],
    [ "EvidenceBaseSwig", "class_evidence_base_swig.html", "class_evidence_base_swig" ],
    [ "EvidenceDeviceDetectionSwig", "class_evidence_device_detection_swig.html", "class_evidence_device_detection_swig" ],
    [ "ExampleFlowElementA", "class_example_flow_element_a.html", "class_example_flow_element_a" ],
    [ "ExampleFlowElementB", "class_example_flow_element_b.html", "class_example_flow_element_b" ],
    [ "ExampleUtils", "class_example_utils.html", "class_example_utils" ],
    [ "FiftyOneDegreesHashEngine", "class_fifty_one_degrees_hash_engine.html", "class_fifty_one_degrees_hash_engine" ],
    [ "GettingStartedConsole", "class_getting_started_console.html", "class_getting_started_console" ],
    [ "GettingStartedWeb", "class_getting_started_web.html", "class_getting_started_web" ],
    [ "IntegerValueSwig", "class_integer_value_swig.html", "class_integer_value_swig" ],
    [ "MapStringStringSwig", "class_map_string_string_swig.html", "class_map_string_string_swig" ],
    [ "MatchMetrics", "class_match_metrics.html", "class_match_metrics" ],
    [ "MetaDataConsole", "class_meta_data_console.html", "class_meta_data_console" ],
    [ "MetaDataSwig", "class_meta_data_swig.html", "class_meta_data_swig" ],
    [ "ProfileMetaDataCollectionSwig", "class_profile_meta_data_collection_swig.html", "class_profile_meta_data_collection_swig" ],
    [ "ProfileMetaDataSwig", "class_profile_meta_data_swig.html", "class_profile_meta_data_swig" ],
    [ "PropertyMetaDataCollectionSwig", "class_property_meta_data_collection_swig.html", "class_property_meta_data_collection_swig" ],
    [ "PropertyMetaDataSwig", "class_property_meta_data_swig.html", "class_property_meta_data_swig" ],
    [ "RequiredPropertiesConfigSwig", "class_required_properties_config_swig.html", "class_required_properties_config_swig" ],
    [ "ResultsBaseSwig", "class_results_base_swig.html", "class_results_base_swig" ],
    [ "ResultsDeviceDetectionSwig", "class_results_device_detection_swig.html", "class_results_device_detection_swig" ],
    [ "ResultsHashSwig", "class_results_hash_swig.html", "class_results_hash_swig" ],
    [ "StringValueSwig", "class_string_value_swig.html", "class_string_value_swig" ],
    [ "ValueMetaDataCollectionSwig", "class_value_meta_data_collection_swig.html", "class_value_meta_data_collection_swig" ],
    [ "ValueMetaDataKeySwig", "class_value_meta_data_key_swig.html", "class_value_meta_data_key_swig" ],
    [ "ValueMetaDataSwig", "class_value_meta_data_swig.html", "class_value_meta_data_swig" ],
    [ "VectorStringSwig", "class_vector_string_swig.html", "class_vector_string_swig" ],
    [ "VectorStringValuesSwig", "class_vector_string_values_swig.html", "class_vector_string_values_swig" ]
];