name: Nightly Publish Main

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: 'true'
        description: Dry Run
    # schedule:
    #   - cron: '0 1 * * *'

jobs:
  Nightly_Publish_Main:
    uses: postindustria-tech/common-ci/.github/workflows/nightly-publish-main.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun }}
      build-platform: ubuntu-latest
      cache-assets: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      asset-keys: '{"DeviceDetection": "${{ secrets.DEVICE_DETECTION_KEY }}", "DeviceDetectionUrl": "${{ secrets.DEVICE_DETECTION_URL }}"}'
