name: Nightly Submodule Update

on:
  workflow_dispatch:
    inputs:
      dryrun:
        default: 'true'
        description: Dry Run
    # schedule:
    #   - cron: '0 0 * * *'

jobs:
  Nightly_Submodule_Update:
    uses: postindustria-tech/common-ci/.github/workflows/nightly-submodule-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
